#!/usr/bin/env python3
"""Make `keelhaul gen-regtest` output compile as a no_std lib crate.

Three fixes, all forced by observed keelhaul behaviour, verified against
svd/TM4C123GH6PM.svd:

1. The generated file has no crate attributes. Prepend #![no_std] and silence
   the non-snake-case test names.
2. keelhaul stamps a generation timestamp into a doc comment. Strip it so the
   crate content is reproducible across runs.
3. Vendor SVDs define the same register twice (alternate/overlaid registers --
   43 of them on the TM4C123, e.g. USB0_TXINTERVAL7, I2C MCS). keelhaul emits
   one `pub fn` per definition, so the raw file fails with E0428. Drop repeats.

Only *byte-identical* duplicates are dropped -- a differing body means two
definitions disagree about the same address, which is a finding, not noise, so
we fail loudly instead of silently picking one.

Prints the number dropped to stderr for the PR comment.
"""

import re
import sys

HEADER = "#![no_std]\n#![allow(non_snake_case)]\n"
FN = re.compile(r"^( *)pub fn (test_\w+)\(\) -> Result<\(\)> \{.*?^\1\}\n", re.S | re.M)
# "Generated by keelhaul vX at <ISO-timestamp>" -> drop the "at <timestamp>".
TIMESTAMP = re.compile(r" at \d{4}-\d\d-\d\dT[0-9:.]+Z")


def fixup(src):
    src = TIMESTAMP.sub("", src)
    seen = {}
    dropped = []

    def sub(m):
        name, body = m.group(2), m.group(0)
        if name not in seen:
            seen[name] = body
            return body
        if seen[name] != body:
            raise SystemExit(
                f"fixup_generated: {name} defined twice with different bodies -- "
                "two SVD definitions disagree about one address. Fix the SVD."
            )
        dropped.append(name)
        return ""

    return HEADER + FN.sub(sub, src), dropped


def main():
    out, dropped = fixup(sys.stdin.read())
    sys.stdout.write(out)
    print(len(dropped), file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
