#!/usr/bin/env python3
"""Run: python3 scripts/test_fixup_generated.py"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from fixup_generated import fixup  # noqa: E402

DUP = """\
#[doc = "Generated by keelhaul v0.1.0 at 2020-01-02T03:04:05Z"]
pub mod usb0 {
    pub fn test_A_0x1() -> Result<()> {
        let v = 1;
        Ok(())
    }
    pub fn test_A_0x1() -> Result<()> {
        let v = 1;
        Ok(())
    }
    pub fn test_B_0x2() -> Result<()> {
        Ok(())
    }
}
"""


def test_drops_identical_duplicate_and_keeps_the_rest():
    out, dropped = fixup(DUP)
    assert dropped == ["test_A_0x1"], dropped
    assert out.startswith("#![no_std]")
    assert out.count("pub fn test_A_0x1") == 1
    assert out.count("pub fn test_B_0x2") == 1


def test_strips_generation_timestamp():
    out, _ = fixup(DUP)
    assert "2020-01-02" not in out
    assert "Generated by keelhaul v0.1.0" in out  # version kept, date gone


def test_differing_duplicate_is_a_hard_failure():
    src = DUP.replace("let v = 1;\n        Ok(())\n    }\n    pub fn test_B",
                      "let v = 999;\n        Ok(())\n    }\n    pub fn test_B")
    try:
        fixup(src)
    except SystemExit as e:
        assert "disagree" in str(e)
        return
    raise AssertionError("expected a hard failure on differing bodies")


if __name__ == "__main__":
    for name, fn in sorted(globals().items()):
        if name.startswith("test_"):
            fn()
    print("ok")
